version: "3.1"
services:
    redis:
        image: "redis:alpine"

    postgres:
        image: "postgres:15-alpine"
        working_dir: /docker
        volumes:
            - "..:/docker"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1111
            - POSTGRES_DB=car-app
        ports:
            - "8084:5432"

    webserver:
        image: "nginx:alpine"
        working_dir: /docker
        volumes:
            - "..:/docker"
            - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "8080:80"

    php-fpm:
        build: docker/php-fpm
        working_dir: /docker
        volumes:
            - "..:/docker"
            - "./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini"
            - "./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/cli/conf.d/99-overrides.ini"
