version: "3.1"
services:
    redis:
        image: "redis:alpine"

    postgres:
        image: "postgres:15-alpine"
        working_dir: /docker
        volumes:
            - ".:/docker"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1111
            - POSTGRES_DB=car-app
        ports:
            - "5432:5432"

    webserver:
        image: "nginx:alpine"
        working_dir: /docker
        volumes:
            - ".:/docker"
            - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/custom.conf"
        ports:
            - "8080:80"

    php-fpm:
        build: docker/php-fpm
        working_dir: /docker
        volumes:
            - ".:/docker"
            - "./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini"
            - "./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/cli/conf.d/99-overrides.ini"
        command: /bin/sh -c "chown -R www-data:www-data /docker/storage && chmod -R 775 /docker/storage && php-fpm8.4"
